PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE TableA (
a INTEGER,
b INTEGER,
common TEXT
);
INSERT INTO TableA VALUES(1,10,'apple');
INSERT INTO TableA VALUES(2,20,'banana');
INSERT INTO TableA VALUES(3,30,'orange');
CREATE TABLE TableB (
c INTEGER,
d INTEGER,
common TEXT
);
INSERT INTO TableB VALUES(100,1000,'apple');
INSERT INTO TableB VALUES(200,2000,'grape');
INSERT INTO TableB VALUES(300,3000,'banana');
COMMIT;
